"""models modified3

Revision ID: 70a3c45226b9
Revises: acd310ec4ab4
Create Date: 2023-09-04 22:15:15.687800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a3c45226b9'
down_revision = 'acd310ec4ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.drop_column('bakery')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bakery', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
